# Generated by Django 4.2.17 on 2026-01-25 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_businessprofile_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(help_text="6-digit OTP code", max_length=6)),
                (
                    "method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")],
                        help_text="OTP delivery method",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="OTP expiration time (10 minutes from creation)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether OTP has been used"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset OTP",
                "verbose_name_plural": "Password Reset OTPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
