# Generated by Django 5.1 on 2026-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postergeneration",
            name="promotion_name",
            field=models.TextField(),
        ),
    ]
